version: '2'
services:
    workplace-app:
        image: workplace
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://workplace-postgresql:5432/workplace
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    workplace-postgresql:
        extends:
            file: postgresql.yml
            service: workplace-postgresql
